version: '3.1'

services:
  
  db:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123123
    ports:
      - "27017:27017"
    deploy:  
      resources:
        limits:
          cpus: "0.5"
          memory: "500M" 

  app:
    build: .
    restart: always
    depends_on:
      - db
    links:
      - "db"
    ports:
      - "5000:5000"